(in-package :how)

(defun start-how ()
  (sdl:with-init (sdl:sdl-init-video )
    (sdl:window *game-frame-size-x* *game-frame-size-y*)
    (setf (sdl:frame-rate) 200)
    (sdl:enable-key-repeat nil nil)
    (let ((house (load-image "house_64x64.bmp"))
	  (dude (make-instance 'how.characters::actor
			       :surface (load-image "stickfigure_64x64.bmp")
			       :name "Igoru"))
	  (dude-position-x 0)
	  (dude-position-y 0))

      (sdl:with-events ()
	(:quit-event () (setf some-debug-stuff (list (sdl::width house) (sdl::height house))) t)
	(:key-repeat-on)
	(:key-down-event (:key key)
			 (when (sdl:key= key :sdl-key-q) (sdl:push-quit-event))
			 (when (sdl:key= key :sdl-key-up) (setf dude-position-y (- dude-position-y 1)))
			 (when (sdl:key= key :sdl-key-down) (setf dude-position-y (+ dude-position-y 1)))
			 (when (sdl:key= key :sdl-key-left) (setf dude-position-x (- dude-position-x 1)))
			 (when (sdl:key= key :sdl-key-right) (setf dude-position-x (+ dude-position-x 1))))
	(:idle ()
	       (sdl:clear-display sdl:*green*)
	       (sdl:draw-surface-at-* house 100 100)
	       (sdl:draw-surface-at-* (how.characters::surface dude)
				      dude-position-x dude-position-y)
	       (how.health::draw-health-at* (make-instance 'how.health::health :current 14 :maximum 20)
					    :y 0 :x (- *game-frame-size-x* (* 10 how.health::*heart-image-side-length*)))
	       (sdl:update-display))))))
;;; END
